package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Zero0x00/cloudrift/internal/aws"
	"github.com/Zero0x00/cloudrift/internal/config"
	"github.com/Zero0x00/cloudrift/internal/graph"
	"github.com/Zero0x00/cloudrift/internal/models"
	"github.com/Zero0x00/cloudrift/internal/output"
	"github.com/Zero0x00/cloudrift/internal/pipeline"
	"github.com/Zero0x00/cloudrift/internal/scans"
)

var version = "dev"

func main() {
	root := newRootCommand()
	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func newRootCommand() *cobra.Command {
	root := &cobra.Command{
		Use:   "cloudrift",
		Short: "Cloudrift discovers orphaned edge assets in AWS orgs",
	}
	cfgPath := root.PersistentFlags().String("config", "", "Path to config TOML")

	var outputDir string
	var neo4jEnabled bool
	scanCmd := &cobra.Command{
		Use:   "scan",
		Short: "Run orphaned-edge scan",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(*cfgPath)
			if err != nil {
				return err
			}
			if outputDir == "" {
				outputDir = cfg.Output.OutputDir
			}
			noHTTP, _ := cmd.Flags().GetBool("no-http")
			if c, _ := cmd.Flags().GetInt("concurrency"); c > 0 {
				cfg.Scan.HTTPProbeConcurrency = c
			}
			if err := ensureValidSession(cmd.Context(), cfg.AWS.ManagementProfile, cmd); err != nil {
				return err
			}
			scanID, err := runScan(cmd.Context(), cfg, outputDir, pipeline.Options{NoHTTP: noHTTP})
			if err != nil {
				return err
			}
			if !neo4jEnabled {
				return nil
			}
			// scanID is generated by runScan (timestamp format); not user-supplied.
			scanPath := filepath.Join(outputDir, scanID)
			return exportScanToNeo4j(context.Background(), cfg, scanPath, defaultNeo4jConnector{})
		},
	}
	scanCmd.Flags().StringVar(&outputDir, "output-dir", "", "Output directory")
	scanCmd.Flags().Bool("no-http", false, "Skip HTTP probing")
	scanCmd.Flags().Int("concurrency", 50, "HTTP probe concurrency")
	scanCmd.Flags().BoolVar(&neo4jEnabled, "neo4j", false, "Write scan projection to Neo4j (Phase 3, optional)")

	var reportScanID, format, reportOut string
	reportCmd := &cobra.Command{
		Use:   "report",
		Short: "Generate report from scan",
		RunE: func(cmd *cobra.Command, args []string) error {
			if reportScanID == "" {
				reportScanID = "latest"
			}
			return runReport(outputDir, reportScanID, format, reportOut)
		},
	}
	reportCmd.Flags().StringVar(&reportScanID, "scan-id", "latest", "Scan ID or \"latest\" (newest by scan-metadata timestamp; tie-break directory name ascending)")
	reportCmd.Flags().StringVar(&format, "format", "table", "table|json|csv|markdown|excel|sarif")
	reportCmd.Flags().StringVar(&reportOut, "output", "", "Output path")
	reportCmd.Flags().StringVar(&outputDir, "output-dir", "./cloudrift-output", "Output directory")

	versionCmd := &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println(version)
		},
	}

	dashboardCmd := newDashboardCommand(cfgPath)
	queryCmd := newQueryCommand(cfgPath)
	demoCmd := newDemoCommand(cfgPath)

	root.AddCommand(scanCmd, reportCmd, queryCmd, versionCmd, dashboardCmd, demoCmd)
	return root
}

// ensureValidSession checks AWS credentials before a scan. If an SSO session is
// expired it auto-triggers `aws sso login` (blocking) and retries. Falls back
// to showing the manual command when the aws CLI is not installed.
func ensureValidSession(ctx context.Context, profile string, cmd *cobra.Command) error {
	err := aws.CheckCredentials(ctx, profile)
	if err == nil {
		return nil
	}
	if !aws.IsSSOExpiredError(err) {
		return fmt.Errorf("AWS credential check failed: %w", err)
	}
	fmt.Fprintf(cmd.OutOrStdout(), "AWS SSO session expired for profile %q\n", profile)
	fmt.Fprintf(cmd.OutOrStdout(), "Opening browser for re-authentication...\n")
	found, loginErr := aws.WaitSSOLogin(ctx, profile)
	if !found {
		return fmt.Errorf("SSO session expired. aws CLI not found — run manually:\n  %s", aws.SSOLoginCommand(profile))
	}
	if loginErr != nil {
		return fmt.Errorf("SSO login failed: %w\nRun manually: %s", loginErr, aws.SSOLoginCommand(profile))
	}
	fmt.Fprintf(cmd.OutOrStdout(), "Session refreshed. Resuming scan...\n")
	return nil
}

func runScan(ctx context.Context, cfg *config.Config, outputDir string, opts pipeline.Options) (string, error) {
	return pipeline.Run(ctx, cfg, outputDir, version, pipeline.NewAWSSource(), opts)
}

type neo4jConnectorFactory interface {
	Connect(ctx context.Context, uri, username, password string) (graph.Execer, func(context.Context) error, error)
}

type neo4jDriverConnector struct{}

func (neo4jDriverConnector) Connect(ctx context.Context, uri, username, password string) (graph.Execer, func(context.Context) error, error) {
	driver, err := newNeo4jDriver(ctx, uri, username, password)
	if err != nil {
		return nil, nil, err
	}
	ex := graph.NewDriverExecer(driver, "")
	closeFn := func(ctx context.Context) error { return driver.Close(ctx) }
	return ex, closeFn, nil
}

// defaultNeo4jConnector is the production connector. Tests inject fakes via neo4jConnectorFactory.
type defaultNeo4jConnector struct{}

func (defaultNeo4jConnector) Connect(ctx context.Context, uri, username, password string) (graph.Execer, func(context.Context) error, error) {
	return neo4jDriverConnector{}.Connect(ctx, uri, username, password)
}

func exportScanToNeo4j(ctx context.Context, cfg *config.Config, scanPath string, c neo4jConnectorFactory) error {
	uri := strings.TrimSpace(cfg.Neo4j.URI)
	user := strings.TrimSpace(cfg.Neo4j.Username)
	passEnv := strings.TrimSpace(cfg.Neo4j.PasswordEnv)
	if uri == "" {
		return errors.New("neo4j export enabled but config neo4j.uri is empty")
	}
	if user == "" {
		return errors.New("neo4j export enabled but config neo4j.username is empty")
	}
	if passEnv == "" {
		return errors.New("neo4j export enabled but config neo4j.password_env is empty")
	}
	pass := os.Getenv(passEnv)
	if strings.TrimSpace(pass) == "" {
		return fmt.Errorf("neo4j export enabled but env var %s is empty or unset", passEnv)
	}

	ex, closeFn, err := c.Connect(ctx, uri, user, pass)
	if err != nil {
		return fmt.Errorf("neo4j connect: %w", err)
	}
	defer func() { _ = closeFn(ctx) }()

	// Intentionally reload from disk (see loadScanArtifactsForGraph) so graph export
	// never depends on in-memory scan state and cannot drift from written JSON.
	meta, assets, rels, findings, err := loadScanArtifactsForGraph(scanPath)
	if err != nil {
		return err
	}

	// Generate embeddings (best-effort) so the vector index is populated for RAG / query.
	graph.AttachEmbeddingsBestEffort(ctx, cfg, &meta, findings)

	for _, ddl := range graph.SchemaStatements() {
		if err := ex.Run(ctx, ddl, nil); err != nil {
			return fmt.Errorf("neo4j schema setup failed: %w", err)
		}
	}
	if err := graph.WriteScan(ctx, ex, meta, assets, rels, findings); err != nil {
		return fmt.Errorf("neo4j export failed: %w", err)
	}
	// Best-effort GDS clustering + centrality (writes community/centrality node properties).
	// Skipped cleanly when the GDS plugin is absent — projection above already succeeded.
	if gerr := graph.RunGDS(ctx, ex, filepath.Base(scanPath)); gerr != nil {
		fmt.Fprintf(os.Stderr, "note: %v\n", gerr)
	}
	return nil
}

// loadScanArtifactsForGraph loads everything graph.WriteScan needs from the scan directory.
//
// Intentional design (do not "optimize" away the disk re-read):
//   - Flat JSON on disk is the canonical scan output; Neo4j is a projection only.
//   - Re-reading after runScan guarantees the graph matches what was persisted, avoids
//     implicit coupling to in-memory collector/scorer state, and keeps export as a
//     small post-step after normal writers finish.
//   - Tradeoff: an extra read pass and sensitivity to artifact layout; that is acceptable
//     here because export is optional and correctness > avoiding duplicate I/O.
//
// Inputs (all under scanPath). Findings are reloaded via loadFindings(filepath.Dir(scanPath),
// filepath.Base(scanPath)); basename must satisfy scans.IsSafeScanID (Neo4j export uses only
// filepath.Join(outputDir, runScan's generated scan ID)).
//   - scan-metadata.json (required)
//   - findings.json (required)
//   - assets/*.json — each file is a JSON array of AssetNode; optional (missing dir => no assets)
//   - relationships.json — JSON array of Relationship; optional (missing file => no rels)
func loadScanArtifactsForGraph(scanPath string) (models.ScanSnapshot, []models.AssetNode, []models.Relationship, []models.Finding, error) {
	var meta models.ScanSnapshot
	b, err := os.ReadFile(filepath.Join(scanPath, "scan-metadata.json"))
	if err != nil {
		return meta, nil, nil, nil, fmt.Errorf("read scan metadata: %w", err)
	}
	if err := json.Unmarshal(b, &meta); err != nil {
		return meta, nil, nil, nil, fmt.Errorf("parse scan metadata: %w", err)
	}

	findings, err := loadFindings(filepath.Dir(scanPath), filepath.Base(scanPath))
	if err != nil {
		return meta, nil, nil, nil, fmt.Errorf("read findings: %w", err)
	}

	assets, err := loadAssets(scanPath)
	if err != nil {
		return meta, nil, nil, nil, err
	}
	rels, err := loadRelationships(scanPath)
	if err != nil {
		return meta, nil, nil, nil, err
	}
	return meta, assets, rels, findings, nil
}

// loadAssets merges every *.json file under assets/ (sorted by name). Each file must
// contain a JSON array of AssetNode. Missing directory is not an error (empty slice).
func loadAssets(scanPath string) ([]models.AssetNode, error) {
	assetsDir := filepath.Join(scanPath, "assets")
	entries, err := os.ReadDir(assetsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read assets dir: %w", err)
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if strings.HasSuffix(e.Name(), ".json") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	var out []models.AssetNode
	for _, name := range names {
		b, err := os.ReadFile(filepath.Join(assetsDir, name))
		if err != nil {
			return nil, fmt.Errorf("read asset file %s: %w", name, err)
		}
		if len(b) == 0 {
			continue
		}
		var nodes []models.AssetNode
		if err := json.Unmarshal(b, &nodes); err != nil {
			return nil, fmt.Errorf("parse asset file %s: %w", name, err)
		}
		out = append(out, nodes...)
	}
	return out, nil
}

// loadRelationships reads relationships.json as a JSON array of Relationship.
// Missing or empty file is not an error (empty slice).
func loadRelationships(scanPath string) ([]models.Relationship, error) {
	path := filepath.Join(scanPath, "relationships.json")
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read relationships: %w", err)
	}
	if len(b) == 0 {
		return nil, nil
	}
	var rels []models.Relationship
	if err := json.Unmarshal(b, &rels); err != nil {
		return nil, fmt.Errorf("parse relationships: %w", err)
	}
	return rels, nil
}

func runReport(outputDir, scanID, format, outPath string) error {
	findings, err := loadFindings(outputDir, scanID)
	if err != nil {
		return err
	}
	// resolveOut returns the explicit --output path, else <scan-dir>/<name>.
	resolveOut := func(name string) (string, error) {
		if outPath != "" {
			return outPath, nil
		}
		resolved, err := resolveScanID(outputDir, scanID)
		if err != nil {
			return "", err
		}
		return filepath.Join(outputDir, resolved, name), nil
	}
	switch format {
	case "table":
		fmt.Print(output.RenderTable(findings))
		return nil
	case "json":
		p, err := resolveOut("report.json")
		if err != nil {
			return err
		}
		return output.WriteJSON(p, findings)
	case "csv":
		p, err := resolveOut("report.csv")
		if err != nil {
			return err
		}
		return output.WriteCSV(p, findings)
	case "markdown":
		p, err := resolveOut("report.md")
		if err != nil {
			return err
		}
		return output.WriteMarkdown(p, findings)
	case "excel", "xlsx":
		p, err := resolveOut("report.xlsx")
		if err != nil {
			return err
		}
		return output.WriteExcel(p, findings)
	case "sarif":
		p, err := resolveOut("report.sarif")
		if err != nil {
			return err
		}
		return output.WriteSARIF(p, findings)
	default:
		return fmt.Errorf("unsupported format: %s (table|json|csv|markdown|excel|sarif)", format)
	}
}

func loadFindings(outputDir, scanID string) ([]models.Finding, error) {
	resolved, err := resolveScanID(outputDir, scanID)
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(filepath.Join(outputDir, resolved, "findings.json"))
	if err != nil {
		return nil, err
	}
	var findings []models.Finding
	if len(b) == 0 {
		return findings, nil
	}
	return findings, json.Unmarshal(b, &findings)
}

func resolveScanID(outputDir, scanID string) (string, error) {
	return scans.ResolveScanDirectoryName(outputDir, scanID)
}

// writeFindings persists findings as JSON. Retained as a small helper used by tests to set up
// scan directories. Report output formats go through internal/output (CSV-injection-safe, plus
// the Excel writer). See runReport.
func writeFindings(path string, findings []models.Finding) error {
	b, err := json.MarshalIndent(findings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}
