jobs:
  tool-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false

      - name: Tidy modules
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Clean Go env
        run: |
          go clean -modcache
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=5m